<?php

namespace App\Http\Requests\Driver;

use Illuminate\Foundation\Http\FormRequest;

class StoreDriverRequest extends FormRequest
{
    public function authorize()
    {
        // Auth is intentionally disabled in this MVP phase.
        return true;
    }

    public function prepareForValidation(): void
    {
        if (! $this->filled('preferred_culture_code')) {
            $this->merge(['preferred_culture_code' => 'de']);
        }
    }

    public function rules()
    {
        return [
            // Optional — auto-generated by DriverController::nextDriverCode()
            // when omitted. Validation still rejects duplicates so SAP /
            // external imports that pass their own code can't collide.
            'driver_code' => 'nullable|string|max:50|unique:drivers,driver_code',
            'first_name' => 'required|string|max:100',
            'last_name' => 'required|string|max:100',

            'national_id_last4' => 'nullable|string|size:4',
            'license_no' => 'nullable|string|max:50',
            'license_expiry_date' => 'nullable|date',

            'phone' => 'nullable|string|max:50',
            'email' => 'nullable|email|max:150',

            'preferred_culture_code' => 'required|string|max:10',

            'training_status' => 'nullable|string|in:valid,expired,missing,not_required,unknown',
            'training_valid_until' => 'nullable|date',

            'employer_company_id' => 'nullable|string|size:36|exists:companies,id',
            'operator_company_id' => 'nullable|string|size:36|exists:companies,id',

            'notes' => 'nullable|string',
            'is_active' => 'nullable|boolean',
        ];
    }
}
