<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Station-View demo telemetry
    |--------------------------------------------------------------------------
    |
    | When true, StationViewItemResource fills the V3.2 station-card
    | extension fields that have no upstream source yet (live_pressure,
    | temperature, target_pressure, analysis_required, safety, maintenance,
    | process_step) with deterministic fake values generated by
    | App\Services\Loading\StationDemoTelemetry.
    |
    | This is for FE demos / kiosk previews only — flip it off the moment
    | a real PLC gateway / maintenance / interlock source lands. Default
    | is `true` outside production so `php artisan migrate:fresh --seed`
    | yields a card UI that looks alive without any extra wiring.
    |
    | Override per environment via STATION_DEMO_TELEMETRY=true|false in .env.
    */

    'demo_telemetry' => env(
        'STATION_DEMO_TELEMETRY',
        env('APP_ENV', 'production') !== 'production'
    ),
];
