<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Station-View demo telemetry
    |--------------------------------------------------------------------------
    |
    | When true, StationViewItemResource fills the V3.2 station-card
    | extension fields that have no upstream source yet (live_pressure,
    | temperature, target_pressure, analysis_required, safety, maintenance,
    | process_step) with deterministic fake values generated by
    | App\Services\Loading\StationDemoTelemetry.
    |
    | This is for FE demos / kiosk previews only — flip it off the moment
    | a real PLC gateway / maintenance / interlock source lands. Default
    | is `true` everywhere (including production) because the MVP / Railway
    | deployment is itself a kiosk demo until the real PLC integration
    | ships. The synthesiser is gated by this single flag so flipping it
    | off later is a one-line change.
    |
    | Override per environment via STATION_DEMO_TELEMETRY=true|false in
    | .env — set it to `false` once real upstream telemetry lands.
    */

    'demo_telemetry' => env('STATION_DEMO_TELEMETRY', true),
];
